#在开始之前需要下载rtool,配置相应的环境变量
install.packages("remotes")
remotes::install_github("stan-dev/cmdstanr")
library(cmdstanr)
#set_cmdstan_path("C:\RTools43\usr\bin")
#C:\RTools\RTools40\usr\bin
install.packages("devtools")
devtools::install_github("stan-dev/cmdstanr")
library(cmdstanr)
install_cmdstan()
